- name: Check status codes using httpx
      run: |
        echo "[*] Running httpx to check status codes..."
        mkdir -p "${{ github.event.inputs.domain }}/httpx"
        httpx -l "${{ github.event.inputs.domain }}/subdomains.txt" -silent -status-code -o "${{ github.event.inputs.domain }}/httpx_output.txt"
        
    - name: Sort domains by HTTP status code
      run: |
        grep "200" "${{ github.event.inputs.domain }}/httpx_output.txt" | awk '{print $1}' > "${{ github.event.inputs.domain }}/200.txt"
        grep -v "200" "${{ github.event.inputs.domain }}/httpx_output.txt" | awk '{print $1}' > "${{ github.event.inputs.domain }}/other_status_codes.txt"

    - name: Send status code files to Telegram bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendDocument" -F chat_id="${{ env.TELEGRAM_CHAT_ID }}" -F document=@"${{ github.event.inputs.domain }}/200.txt"
        curl -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendDocument" -F chat_id="${{ env.TELEGRAM_CHAT_ID }}" -F document=@"${{ github.event.inputs.domain }}/other_status_codes.txt"

    - name: Download wordlist for ffuf
      run: |
        curl -o common.txt https://raw.githubusercontent.com/jahanaj098/shhhhhh/refs/heads/main/wordlists/common.txt

    - name: Fuzz with ffuf for 200 OK domains
      run: |
        mkdir -p "${{ github.event.inputs.domain }}/fuzzing_200"
        ffuf -u "http://FUZZ.${{ github.event.inputs.domain }}" -w common.txt -ac -mc 200 -o "${{ github.event.inputs.domain }}/fuzzing_200/results.json"
        # Screenshot capture for any found directories or files
        puppeteer --headless --screenshot --output="${{ github.event.inputs.domain }}/fuzzing_200/screenshot.png" "http://FUZZ.${{ github.event.inputs.domain }}"

    - name: Fuzz with ffuf for other status code domains
      run: |
        mkdir -p "${{ github.event.inputs.domain }}/fuzzing_other"
        ffuf -u "http://FUZZ.${{ github.event.inputs.domain }}" -w common.txt -ac -mc 400-599 -o "${{ github.event.inputs.domain }}/fuzzing_other/results.json"
        # Screenshot capture for any found directories or files
        puppeteer --headless --screenshot --output="${{ github.event.inputs.domain }}/fuzzing_other/screenshot.png" "http://FUZZ.${{ github.event.inputs.domain }}"

    - name: Zip the results
      run: |
        zip -r "${{ github.event.inputs.domain }}/final.zip" "${{ github.event.inputs.domain }}"
        
    - name: Send final.zip to Telegram bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendDocument" -F chat_id="${{ env.TELEGRAM_CHAT_ID }}" -F document=@"${{ github.event.inputs.domain }}/final.zip"
